Select 
	DOCID, CONAM, COCITY, COST, COPH, COACT, COY, COBOD, INDX, AUDIT_ID, AUDIT_DATE, COPHAC, COCNTY, COZIP, COADD1, COADD2, COFAXAC, COFAX, COCNTRY, COPHONENBR, COFAXNBR, 
                         GDLastTouched 
From  ${db_epr}.${schema}.DOCDB_COMORGX;