Select 
	DOCID, INDX, AUDIT_ID, AUDIT_DATE, MILCMDR, MILRANK, MILSERV, MILSVCNUM, MILDIS, MILFMD, MILFMM, MILFMY, MILTOD, MILTOM, MILTOY, Sort_Order, FromDate, ToDate, ACTIVE_FLAG, 
                         MILCMDRFNAM, MILCMDRLNAM, MILCMDRMI, MILCMDRTTL, GDLastTouched
From  ${db_epr}.${schema}.DOCDB_MILX;