Select 
	DOCID, INDX, NOTEDATEM, NOTEDATED, NOTEDATEY, NOTE, NOTECAT, NOTEUSER, DELFLAG, REFNUM, AUDIT_ID, AUDIT_DATE, NOTESUBJECT, ACTIVE_FLAG, NoteDate, GDLastTouched
From  ${db_epr}.${schema}.DOCDB_GENNOTES;