Select 
	EXTDEG, EXTLICISST, EXTLICNUM, EXTNAM, EXTPRACADD1, EXTPRACCITY, EXTPRACNAM, EXTPRACST, EXTPRACZIP, AUDIT_ID, AUDIT_DATE, DOCID, REC_NUM, REPORT_NAME, REPORT_DATE, INDX, 
                         EXTPRACADD2, EXTPRACCNTRY, EXTPRACCNTY, EXTFNAM, EXTLNAM, EXTMI, DateCreated, CreatedBy, DateModified, ModifiedBy, Active_Flag, GDLastTouched 
From  ${db_epr}.${schema}.DOCDB_EXT;