Select 
	DOCID, LEOTYP, LEONUM, LEOEXM, LEOEXD, LEOEXY, LEOST, INDX, LEOISD, LEOISM, LEOISY, AUDIT_ID, AUDIT_DATE, LEOEXF, LEOISF, LECECF1, LECECF2, LECECFMGISFDT1, LECECFMGISFDT2, 
                         ACTIVE_FLAG, Sort_Order, leoexpdate, LEOLIMITED, LEOLICNAME, LEODATEAPPLIEDD, LEODATEAPPLIEDM, LEODATEAPPLIEDY, LEOTYPE, LEOLICTYPE, LEORECORDCREATEDDATE, 
                         LEORECORDCREATEDBY, LEODATEAPPMAILEDTORN, LEODATEAPPRETURNEDBYRN, LEORECORDUPDATEDBY, LEORECORDUPDATEDDATE, leoissdate, FromDate, ToDate, DateCreated, CreatedBy, 
                         DateModified, ModifiedBy, LEOSponsor, LEOSponsorDocId, ident, GDLastTouched 
From  ${db_epr}.${schema}.DOCDB_LICENX;