SELECT DOCID
      ,REFNAM
      ,REFINST
      ,REFTTL
      ,REFCITY
      ,REFST
      ,REFPH
      ,REFPHAC
      ,REFREL
      ,REFFMY
      ,REFTOY
      ,DELFLAG
      ,REFRNUM
      ,REFADD1
      ,REFSPEC
      ,REFZIP
      ,INDX
      ,AUDIT_ID
      ,AUDIT_DATE
      ,REFADD2
      ,REFFMM
      ,REFFMD
      ,REFTOM
      ,REFTOD
      ,REFCNTRY
      ,REFCNTY
      ,REFLNAM
      ,REFFNAM
      ,REFADDNUM
      ,REFADDSTREET
      ,Sort_Order
      ,REFFAXAC
      ,REFFAX
      ,REFPREFIX
      ,ident
      ,REFPHEXT
      ,REFEMAIL
      ,FromDate
      ,ToDate
      ,Active_Flag
      ,DateCreated
      ,CreatedBy
      ,DateModified
      ,ModifiedBy
      ,REFPHONENBR
      ,REFFAXNBR
      ,REFFacility
      ,REFDocId
      ,REFMI
      ,GDLastTouched

FROM 
    ${db_epr}.${schema}.DOCDB_REFX
;