Select 
	DOCID, PSLNAM, PSFNAM, PSMI, PSSUFX, PSSSN, PSCITZ, PSPOB, PSDOBM, PSDOBD, PSDOBY, PSHA1, PSHA2, PSCITY, PSST, PSZIP, PSHPH, PSCELL, PSPAGE, PSEMAIL, PSEMRG, PSSPOS, SEX, 
                         PSDEGREE, PSTAXID, PSLANG1, PSLANG2, PSLANG3, AUDIT_ID, AUDIT_DATE, PSFULLNAME, PSDIVORCED, PSDOBFDT, PSHPHF, PSLANG, PSMARRIED, PSPAGENUMF, PSPOBCITY, PSPOBCNTRY, 
                         PSPOBCNTY, PSPOBST, PSSEXF, PSSEXM, PSSINGLE, PSUPIN, PSVISAEXFDT, PSVISASTATUS, PSWIDOWED, PSSEX, PSMSTATUS, PSVISAEXM, PSVISAEXD, PSVISAEXY, PSHACPH, PSCELLAC, PSCELLPH, 
                         PSPAGENUMAC, PSPAGENUMPH, PSEMRGFNAM, PSEMRGMI, PSEMRGLNAM, PSHFAXAC, PSHFAX, PSADD1, PSADD2, PSPHAC, PSPH, PSCNTRY, PSCNTY, PSEMRGPHAC, PSEMRGPH, PSFAXAC, PSFAX, 
                         PSAKAMAIDENNAM, PSPREFIX, PSTBTESTDATE, PrivStatus, PrivReAppDate, PrivLastReAppDate, PrivInitPrivDate, PSDRIVELIC, PSVISANUM, PSACLS, PSBLS, UserDefinedID, PSBLSCERTNUM, PSBLSEXPDATE, 
                         PSACLSCERTNUM, PSACLSEXPDATE, PSPALS, PSPALSCERTNUM, PSPALSEXPDATE, PSDRIVELICST, PSLANG1CAQHCODE, PSLANG2CAQHCODE, PSLANG3CAQHCODE, PSADDNUM, PSADDSTREET, 
                         PSDRIVELICEXPDATE, PSATLS, PSNRP, PSATLSEXPDATE, PSNRPEXPDATE, PSNRPCERTNUM, PSATLSCERTNUM, PSPALSINSTR, PSNRPINSTR, PSBLSINSTR, PSACLSINSTR, PSATLSINSTR, USERDEFINEDID2, 
                         PRIVSTATUSLIMIT, PSNPI, PSPRVDRTYPE, Ident, PSPAGENUMPIN, PSOTHLNAM, PSOTHFNAM, PSOTHMI, PSNRCNTRY, PSRECORDCREATEDDATE, PSRECORDCREATEDBY, PSRECORDUPDATEDDATE, 
                         PSRECORDUPDATEDBY, PSALSOCERTNUM, PSALSO, PSALSOEXPDATE, PSALSOINSTR, PSLINUMBER, PSCELLCARRIER, PSCAQH, PSCAQHDATE, PSTBEXPDATE, PSDOB, PSPHONE, PSVISAEX, 
                         DUESRECDATE, ATTESTATIONDATE, nrpexpdate, PSAGE, hidePractitionerHomeData_YN, PSEmrgPhoneNbr, GMCRefNo, NaturalizationDate, ImmigrationSponsor, PSSecondaryEmail, PSAKAMaidenNamFrom, 
                         PSAKAMaidenNamTo, PSLANG1Fluency, PSLANG2Fluency, PSLANG3Fluency, PSSecondaryADD1, PSSecondaryADD2, PSSecondaryCITY, PSSecondaryST, PSSecondaryZIP, PSSecondaryCNTY, 
                         PSSecondaryCNTRY, PSSecondaryHomeAddrDateFrom, PSSecondaryHomeAddrDateTo, PSSecondaryHomeAddrYearsAtCalc, PSSecondaryFax, PSSECPH, PSDirExchAddr, PSALIAS2, PSALIAS3, PSALIAS4, 
                         PSSPOSFNAM, PSSPOSLNAM, PSSPOSMI, GDLastTouched
From  ${db_epr}.${schema}.DocDB_Personal;