TRUNCATE TABLE stg_ucent_DOCDB_HOSPX;

INSERT /*+direct*/ INTO stg_ucent_DOCDB_HOSPX
(	 
	DOCID, PHNAM, PHTOM, PHCITY, PHST, PHZIP, PHDEPT, PHSUB, PHHEAD, PHTOD, PHTOY, PHRNUM, INDX, AUDIT_ID, AUDIT_DATE, PHADD1, PHADMPYR, PHNAST, PHPCNTAADM, PHSPEC, PHSTFSTAT, 
                         PHNAADD1, PHNACITY, PHNAADMPYR, PHNANAM, PHNAZIP, PHNAPVDRNAM, PHNAPVDRLICNUM, PHNAPVDRLICISST, PHNAPVDRBCYN, ADMIT_PRIV_FLAG, PHNAPVDRPAGEAC, PHNAPVDRPAGE, PHFMM, 
                         PHFMD, PHFMY, PHADD2, PHCNTRY, PHCNTY, PHFAX, PHFAXAC, PHNACNTRY, PHNACNTY, PHNAPH, PHNAPHAC, PHPH, PHPHAC, ACTIVE_FLAG, PHNAPVDRPH, PHNAPVDRPHAC, PHNAPCNTAADM, 
                         PHNAFAXAC, PHNAFAX, PHNAADD2, PHAHPVDRBCYN, PHAHZIP, PHNASTFSTAT, PHNASPEC, PHNAHEAD, PHNADEPT, PHNAFMM, PHNAFMD, PHNAFMY, PHNATOM, PHNATOD, PHNATOY, PHADDNUM, 
                         PHADDSTREET, Sort_Order, PHAHP, PHTYPE, FromDate, ToDate, PHURL, PHEMAIL, DateCreated, CreatedBy, DateModified, ModifiedBy, PHPHONENBR, PHFAXNBR, PHNAPVDRPHONENBR, 
                         PHNAPVDRPAGERNBR, GDLastTouched, 
	sys_hash,
	sys_capture_date
)

SELECT  
	DOCID, PHNAM, PHTOM, PHCITY, PHST, PHZIP, PHDEPT, PHSUB, PHHEAD, PHTOD, PHTOY, PHRNUM, INDX, AUDIT_ID, AUDIT_DATE, PHADD1, PHADMPYR, PHNAST, PHPCNTAADM, PHSPEC, PHSTFSTAT, 
                         PHNAADD1, PHNACITY, PHNAADMPYR, PHNANAM, PHNAZIP, PHNAPVDRNAM, PHNAPVDRLICNUM, PHNAPVDRLICISST, PHNAPVDRBCYN, ADMIT_PRIV_FLAG, PHNAPVDRPAGEAC, PHNAPVDRPAGE, PHFMM, 
                         PHFMD, PHFMY, PHADD2, PHCNTRY, PHCNTY, PHFAX, PHFAXAC, PHNACNTRY, PHNACNTY, PHNAPH, PHNAPHAC, PHPH, PHPHAC, ACTIVE_FLAG, PHNAPVDRPH, PHNAPVDRPHAC, PHNAPCNTAADM, 
                         PHNAFAXAC, PHNAFAX, PHNAADD2, PHAHPVDRBCYN, PHAHZIP, PHNASTFSTAT, PHNASPEC, PHNAHEAD, PHNADEPT, PHNAFMM, PHNAFMD, PHNAFMY, PHNATOM, PHNATOD, PHNATOY, PHADDNUM, 
                         PHADDSTREET, Sort_Order, PHAHP, PHTYPE, FromDate, ToDate, PHURL, PHEMAIL, DateCreated, CreatedBy, DateModified, ModifiedBy, PHPHONENBR, PHFAXNBR, PHNAPVDRPHONENBR, 
                         PHNAPVDRPAGERNBR, GDLastTouched,
	sys_hash,
	sys_capture_date
FROM
	src_ucent_DOCDB_HOSPX;