TRUNCATE TABLE stg_Ucent_DocDB_ProviderFacilitySpecificData;

INSERT /*+direct*/ INTO stg_Ucent_DocDB_ProviderFacilitySpecificData
(
DocDB_ProviderFacilitySpecificData_ID
      ,DocID
      ,FacilityID
      ,PrivStatus
      ,PrivReAppDate
      ,PrivLastReAppDate
      ,PrivInitPrivDate
      ,AUDIT_ID
      ,PRIVSTATUSLIMIT
      ,PROCESS_STATUS
      ,TERM_REASON
      ,TERM_DATE
      ,TERM_NOTE
      ,audit_date
      ,SPEC1
      ,SPEC2
      ,DEPT1
      ,DEPT2
      ,SECTION1
      ,SECTION2
      ,DUES
      ,DUESDATE
      ,UserDefinedID
      ,UserDefinedID2
      ,PR_privStatusRestriction
      ,PR_privStatusRestrictionText
      ,PR_ConfidentialAgreement
      ,PR_AgreementExpDate
      ,PR_Committee_YN
      ,DUESRECDATE
      ,ATTESTATIONDATE
      ,ReCredDate
      ,EmploymentStatus
      ,PROVOPPEDATE
      ,DateCreated
      ,CreatedBy
      ,DateModified
      ,ModifiedBy
      ,PCPType
      ,LOA_YN
      ,LOAReturnDate
      ,datesubmitted
      ,dateaccepted
      ,UserDefinedID3
      ,EPFacilityID
      ,ProviderPublicInformation
      ,PracID
      ,PracSubID
      ,VerificationLetters_YN
      ,TempBeginDate
      ,TempEndDate
      ,LOA_Reason
      ,LOA_Date
      ,LOA_Note
      ,NotificationDate
      ,ProjectedStartDate
      ,LOA_StartDate
      ,LOA_EndDate
      ,Suspended_StartDate
      ,Suspended_EndDate
      ,SuspendedLOA_HistoryID
      ,Suspended_YN
      ,Suspended_Note
      ,Suspended_Reason
      ,MedicareAckDate
      ,RoundingPrefs
      ,CallingPrefs
      ,CredCommitteeDate
      ,MECApprovalDate
      ,BoardApprovalDate
      ,GDLastTouched
	,sys_hash,
	sys_capture_date
)

SELECT DocDB_ProviderFacilitySpecificData_ID
      ,DocID
      ,FacilityID
      ,PrivStatus
      ,PrivReAppDate
      ,PrivLastReAppDate
      ,PrivInitPrivDate
      ,AUDIT_ID
      ,PRIVSTATUSLIMIT
      ,PROCESS_STATUS
      ,TERM_REASON
      ,TERM_DATE
      ,TERM_NOTE
      ,audit_date
      ,SPEC1
      ,SPEC2
      ,DEPT1
      ,DEPT2
      ,SECTION1
      ,SECTION2
      ,DUES
      ,DUESDATE
      ,UserDefinedID
      ,UserDefinedID2
      ,PR_privStatusRestriction
      ,PR_privStatusRestrictionText
      ,PR_ConfidentialAgreement
      ,PR_AgreementExpDate
      ,PR_Committee_YN
      ,DUESRECDATE
      ,ATTESTATIONDATE
      ,ReCredDate
      ,EmploymentStatus
      ,PROVOPPEDATE
      ,DateCreated
      ,CreatedBy
      ,DateModified
      ,ModifiedBy
      ,PCPType
      ,LOA_YN
      ,LOAReturnDate
      ,datesubmitted
      ,dateaccepted
      ,UserDefinedID3
      ,EPFacilityID
      ,ProviderPublicInformation
      ,PracID
      ,PracSubID
      ,VerificationLetters_YN
      ,TempBeginDate
      ,TempEndDate
      ,LOA_Reason
      ,LOA_Date
      ,LOA_Note
      ,NotificationDate
      ,ProjectedStartDate
      ,LOA_StartDate
      ,LOA_EndDate
      ,Suspended_StartDate
      ,Suspended_EndDate
      ,SuspendedLOA_HistoryID
      ,Suspended_YN
      ,Suspended_Note
      ,Suspended_Reason
      ,MedicareAckDate
      ,RoundingPrefs
      ,CallingPrefs
      ,CredCommitteeDate
      ,MECApprovalDate
      ,BoardApprovalDate
      ,GDLastTouched
	,sys_hash,
	sys_capture_date
FROM
	src_Ucent_DocDB_ProviderFacilitySpecificData;