TRUNCATE TABLE stg_ucent_DOCDB_LICENX;

INSERT /*+direct*/ INTO stg_ucent_DOCDB_LICENX
(	 
	DOCID, LEOTYP, LEONUM, LEOEXM, LEOEXD, LEOEXY, LEOST, INDX, LEOISD, LEOISM, LEOISY, AUDIT_ID, AUDIT_DATE, LEOEXF, LEOISF, LECECF1, LECECF2, LECECFMGISFDT1, LECECFMGISFDT2, 
                         ACTIVE_FLAG, Sort_Order, leoexpdate, LEOLIMITED, LEOLICNAME, LEODATEAPPLIEDD, LEODATEAPPLIEDM, LEODATEAPPLIEDY, LEOTYPE, LEOLICTYPE, LEORECORDCREATEDDATE, 
                         LEORECORDCREATEDBY, LEODATEAPPMAILEDTORN, LEODATEAPPRETURNEDBYRN, LEORECORDUPDATEDBY, LEORECORDUPDATEDDATE, leoissdate, FromDate, ToDate, DateCreated, CreatedBy, 
                         DateModified, ModifiedBy, LEOSponsor, LEOSponsorDocId, ident, GDLastTouched, 
	sys_hash,
	sys_capture_date
)

SELECT  
	DOCID, LEOTYP, LEONUM, LEOEXM, LEOEXD, LEOEXY, LEOST, INDX, LEOISD, LEOISM, LEOISY, AUDIT_ID, AUDIT_DATE, LEOEXF, LEOISF, LECECF1, LECECF2, LECECFMGISFDT1, LECECFMGISFDT2, 
                         ACTIVE_FLAG, Sort_Order, leoexpdate, LEOLIMITED, LEOLICNAME, LEODATEAPPLIEDD, LEODATEAPPLIEDM, LEODATEAPPLIEDY, LEOTYPE, LEOLICTYPE, LEORECORDCREATEDDATE, 
                         LEORECORDCREATEDBY, LEODATEAPPMAILEDTORN, LEODATEAPPRETURNEDBYRN, LEORECORDUPDATEDBY, LEORECORDUPDATEDDATE, leoissdate, FromDate, ToDate, DateCreated, CreatedBy, 
                         DateModified, ModifiedBy, LEOSponsor, LEOSponsorDocId, ident, GDLastTouched,
	sys_hash,
	sys_capture_date
FROM
	src_ucent_DOCDB_LICENX;