TRUNCATE TABLE stg_ucent_DOCDB_EXT;

INSERT /*+direct*/ INTO stg_ucent_DOCDB_EXT
(	 
	EXTDEG, EXTLICISST, EXTLICNUM, EXTNAM, EXTPRACADD1, EXTPRACCITY, EXTPRACNAM, EXTPRACST, EXTPRACZIP, AUDIT_ID, AUDIT_DATE, DOCID, REC_NUM, REPORT_NAME, REPORT_DATE, INDX, 
                         EXTPRACADD2, EXTPRACCNTRY, EXTPRACCNTY, EXTFNAM, EXTLNAM, EXTMI, DateCreated, CreatedBy, DateModified, ModifiedBy, Active_Flag, GDLastTouched, 
	sys_hash,
	sys_capture_date
)

SELECT  
	EXTDEG, EXTLICISST, EXTLICNUM, EXTNAM, EXTPRACADD1, EXTPRACCITY, EXTPRACNAM, EXTPRACST, EXTPRACZIP, AUDIT_ID, AUDIT_DATE, DOCID, REC_NUM, REPORT_NAME, REPORT_DATE, INDX, 
                         EXTPRACADD2, EXTPRACCNTRY, EXTPRACCNTY, EXTFNAM, EXTLNAM, EXTMI, DateCreated, CreatedBy, DateModified, ModifiedBy, Active_Flag, GDLastTouched,
	sys_hash,
	sys_capture_date
FROM
	src_ucent_DOCDB_EXT;