TRUNCATE TABLE stg_ucent_DOCDB_GENNOTES;

INSERT /*+direct*/ INTO stg_ucent_DOCDB_GENNOTES
(	 
	DOCID, INDX, NOTEDATEM, NOTEDATED, NOTEDATEY, NOTE, NOTECAT, NOTEUSER, DELFLAG, REFNUM, AUDIT_ID, AUDIT_DATE, NOTESUBJECT, ACTIVE_FLAG, NoteDate, GDLastTouched, 
	sys_hash,
	sys_capture_date
)

SELECT  
	DOCID, INDX, NOTEDATEM, NOTEDATED, NOTEDATEY, NOTE, NOTECAT, NOTEUSER, DELFLAG, REFNUM, AUDIT_ID, AUDIT_DATE, NOTESUBJECT, ACTIVE_FLAG, NoteDate, GDLastTouched,
	sys_hash,
	sys_capture_date
FROM
	src_ucent_DOCDB_GENNOTES;