TRUNCATE TABLE stg_ucent_DOCDB_APPTS;

INSERT /*+direct*/ INTO stg_ucent_DOCDB_APPTS
(	 
		DOCID, INDX, AUDIT_ID, AUDIT_DATE, AAINSTCITY, AAINSTCNTRY, AAINSTNAM, AAINSTST, AADEPT, AATOM, AATOD, AATOY, AAFMM, AAFMD, AAFMY, AAINSTADD1, AAINSTZIP, AASPEC, AADEPTHD, 
                         AAINSTADD2, AAINSTCNTY, AAINSTFAXAC, AAINSTFAX, AAINSTPH, AAINSTPHAC, FromDate, ToDate, AARANK, AAINSTPHONENBR, AAINSTFAXNBR, DateCreated, CreatedBy, DateModified, ModifiedBy, 
                         Active_Flag, GDLastTouched, 
	sys_hash,
	sys_capture_date
)

SELECT  
		DOCID, INDX, AUDIT_ID, AUDIT_DATE, AAINSTCITY, AAINSTCNTRY, AAINSTNAM, AAINSTST, AADEPT, AATOM, AATOD, AATOY, AAFMM, AAFMD, AAFMY, AAINSTADD1, AAINSTZIP, AASPEC, AADEPTHD, 
                         AAINSTADD2, AAINSTCNTY, AAINSTFAXAC, AAINSTFAX, AAINSTPH, AAINSTPHAC, FromDate, ToDate, AARANK, AAINSTPHONENBR, AAINSTFAXNBR, DateCreated, CreatedBy, DateModified, ModifiedBy, 
                         Active_Flag, GDLastTouched,
	sys_hash,
	sys_capture_date
FROM
	src_ucent_DOCDB_APPTS;