TRUNCATE TABLE stg_ucent_DOCDB_COMORGX;

INSERT /*+direct*/ INTO stg_ucent_DOCDB_COMORGX
(	 
	DOCID, CONAM, COCITY, COST, COPH, COACT, COY, COBOD, INDX, AUDIT_ID, AUDIT_DATE, COPHAC, COCNTY, COZIP, COADD1, COADD2, COFAXAC, COFAX, COCNTRY, COPHONENBR, COFAXNBR, 
                         GDLastTouched, 
	sys_hash,
	sys_capture_date
)

SELECT  
	DOCID, CONAM, COCITY, COST, COPH, COACT, COY, COBOD, INDX, AUDIT_ID, AUDIT_DATE, COPHAC, COCNTY, COZIP, COADD1, COADD2, COFAXAC, COFAX, COCNTRY, COPHONENBR, COFAXNBR, 
                         GDLastTouched,
	sys_hash,
	sys_capture_date
FROM
	src_ucent_DOCDB_COMORGX;