TRUNCATE TABLE stg_Ucent_DOCDB_PRACX;

INSERT /*+direct*/ INTO stg_Ucent_DOCDB_PRACX
(
PGADD1
      ,PGADD2
      ,PGCITY
      ,PGST
      ,PGZIP
      ,PGCONT
      ,DOCID
      ,PGGRP
      ,PGORG
      ,PGTOM
      ,PGTOD
      ,PGTOY
      ,PGRNUM
      ,INDX
      ,AUDIT_ID
      ,AUDIT_DATE
      ,PGJOBTTL
      ,PGNEWADD1
      ,PGNEWCITY
      ,PGNEWGRP
      ,PGNEWJOBTTL
      ,PGNEWPH
      ,PGNEWST
      ,PGNEWSUPVNAM
      ,PGNEWSUPVTTL
      ,PGNEWTAXID
      ,PGNEWZIP
      ,PGRFL
      ,PGSUPVNAM
      ,PGSUPVTTL
      ,PGTAXID
      ,PGPHAC
      ,PGPH
      ,PGFMD
      ,PGFMM
      ,PGFMY
      ,PGNEWFMM
      ,PGNEWFMD
      ,PGNEWFMY
      ,PGCNTRY
      ,PGCNTY
      ,PGNEWCNTRY
      ,PGNEWCNTY
      ,PGNEWORG
      ,PGNEWPHAC
      ,PGNEWADD2
      ,PGNEWCONT
      ,PGADDNUM
      ,PGADDSTREET
      ,Sort_Order
      ,PGFAXAC
      ,PGFAX
      ,PGDESCDUTIES
      ,PGEMPSTATUS
      ,PGNUMHRSWRKDWKLY
      ,PGPHEXT
      ,FromDate
      ,ToDate
      ,PGPhoneNbr
      ,PGFaxNbr
      ,DateCreated
      ,CreatedBy
      ,DateModified
      ,ModifiedBy
      ,Active_Flag
      ,PGSUPVFNAM
      ,PGSUPVLNAM
      ,PGSUPVMI
      ,GDLastTouched
	,sys_hash,
	sys_capture_date
)

SELECT PGADD1
      ,PGADD2
      ,PGCITY
      ,PGST
      ,PGZIP
      ,PGCONT
      ,DOCID
      ,PGGRP
      ,PGORG
      ,PGTOM
      ,PGTOD
      ,PGTOY
      ,PGRNUM
      ,INDX
      ,AUDIT_ID
      ,AUDIT_DATE
      ,PGJOBTTL
      ,PGNEWADD1
      ,PGNEWCITY
      ,PGNEWGRP
      ,PGNEWJOBTTL
      ,PGNEWPH
      ,PGNEWST
      ,PGNEWSUPVNAM
      ,PGNEWSUPVTTL
      ,PGNEWTAXID
      ,PGNEWZIP
      ,PGRFL
      ,PGSUPVNAM
      ,PGSUPVTTL
      ,PGTAXID
      ,PGPHAC
      ,PGPH
      ,PGFMD
      ,PGFMM
      ,PGFMY
      ,PGNEWFMM
      ,PGNEWFMD
      ,PGNEWFMY
      ,PGCNTRY
      ,PGCNTY
      ,PGNEWCNTRY
      ,PGNEWCNTY
      ,PGNEWORG
      ,PGNEWPHAC
      ,PGNEWADD2
      ,PGNEWCONT
      ,PGADDNUM
      ,PGADDSTREET
      ,Sort_Order
      ,PGFAXAC
      ,PGFAX
      ,PGDESCDUTIES
      ,PGEMPSTATUS
      ,PGNUMHRSWRKDWKLY
      ,PGPHEXT
      ,FromDate
      ,ToDate
      ,PGPhoneNbr
      ,PGFaxNbr
      ,DateCreated
      ,CreatedBy
      ,DateModified
      ,ModifiedBy
      ,Active_Flag
      ,PGSUPVFNAM
      ,PGSUPVLNAM
      ,PGSUPVMI
      ,GDLastTouched
	,sys_hash,
	sys_capture_date
FROM
	src_Ucent_DOCDB_PRACX;