TRUNCATE TABLE stg_ucent_DOCDB_INSURE;

INSERT /*+direct*/ INTO stg_ucent_DOCDB_INSURE
(	 
	DOCID, INCNAM, Friendly_Name, INCAGNT, INCPH, INCTYP, INCPNUM, INCRETROM, INCRETROD, INCRETROY, INCSTM, INCSTD, INCSTY, INCFM, INCFD, INCFY, INCTO, INCAGG, INSNUM, INDX, AUDIT_ID, 
                         AUDIT_DATE, INCZIP, INCST, INCCITY, INCADD1, INCPHAC, INCCNTRY, INCCNTY, INCUMBAMT, INCYRSWC, ACTIVE_FLAG, INCFAXAC, INCFAX, INCPHF, INCADD2, INCADDNUM, INCADDSTREET, Sort_Order, 
                         incexpdate, ins_id, ins_subID, INCRETRODate, INCSTDate, INCFDate, RetroDate, StartDate, DateCreated, CreatedBy, DateModified, ModifiedBy, INCNAIC, INCPHONENBR, INCFAXNBR, INCEmail, INCAGNTFNAM, 
                         INCAGNTLNAM, INCAGNTMI, GDLastTouched, 
	sys_hash,
	sys_capture_date
)

SELECT  
	DOCID, INCNAM, Friendly_Name, INCAGNT, INCPH, INCTYP, INCPNUM, INCRETROM, INCRETROD, INCRETROY, INCSTM, INCSTD, INCSTY, INCFM, INCFD, INCFY, INCTO, INCAGG, INSNUM, INDX, AUDIT_ID, 
                         AUDIT_DATE, INCZIP, INCST, INCCITY, INCADD1, INCPHAC, INCCNTRY, INCCNTY, INCUMBAMT, INCYRSWC, ACTIVE_FLAG, INCFAXAC, INCFAX, INCPHF, INCADD2, INCADDNUM, INCADDSTREET, Sort_Order, 
                         incexpdate, ins_id, ins_subID, INCRETRODate, INCSTDate, INCFDate, RetroDate, StartDate, DateCreated, CreatedBy, DateModified, ModifiedBy, INCNAIC, INCPHONENBR, INCFAXNBR, INCEmail, INCAGNTFNAM, 
                         INCAGNTLNAM, INCAGNTMI, GDLastTouched,
	sys_hash,
	sys_capture_date
FROM
	src_ucent_DOCDB_INSURE;